name: Create Release and Upload Tarball

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: NPM pack
        id: npm_pack
        run: |
          cd ./Packages/com.github.adaptivehaptics.adapticsengine
          FILE=$(npm pack | tail -n 1)
          echo ::set-output name=file::${FILE}
          mv ${FILE} ../..

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.npm_pack.outputs.file }}
          generate_release_notes: true